gym/urls.py
from django.urls import path
from . import views

app_name = 'gym'
urlpatterns = [
    path('',views.TrainerListView.as_view(),name='trainer_list'), #to view list of trainers
    path('client/<pk>/', views.clientProfileView,name='client_profile'), # to view client profile
    path('trainer_profile/', views.trainerProfileView,name='trainer_profile'),
    path('complete/<pk>/', views.complete,name='complete'),
    path('client_pending/', views.clientPendingView,name='client_pending'),
    # path('profile/', views.profileView.statusChange,name='status'),
    path('trainer_register/',views.trainerRegister, name='trainer_signup'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    # path('stripe_form/',views.stripeForm, name='stripe_form'),
    # path('stripe_register/',views.stripeRegister, name='stripe_register'),
    path('client_register/',views.clientRegister, name='client_signup'),
    path('trainers/<pk>/',views.TrainerDetailView.as_view(),name='trainer_detail'),
    path('client/<pk>/',views.ClientDetailView.as_view(),name='client_detail'), #to update client info
    # path('create/',views.WorkoutCreateView.as_view(),name='workout_create'),
    path('update/<pk>/',views.WorkoutUpdateView.as_view(),name='workout_update'),
    path('trainers/<pk>/workout',views.addWorkout,name='addWorkout'),
    path('workout/<pk>/remove',views.deleteWorkout,name='workout_remove'),
    path('trainer/update/<pk>/',views.TrainerUpdateView.as_view(),name='trainer_update'),
    path('client/update/<pk>/',views.ClientUpdateView.as_view(),name='client_update'),

]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/',views.thanks,name='thanks'),
    path('history/', views.orderHistory,name='order_history'),
    path('<int:order_id>/', views.viewOrder,name='order_detail'),
    path('history/trainer', views.trainerOrderHistory,name='trainer_order_history'),
]

trainer_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('',include('gym.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('stripe/', include('stripe_details.urls')),
    # path('session/', include('session.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/models.py
from django.db import models


class Order(models.Model):
    #this will take information from the stripe form
    client_name = models.CharField(max_length=250, default='none')
    trainer_name = models.CharField(max_length=250, default='none') #new addition
    token = models.CharField(max_length=250,blank=True)
    total = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='GBP Order Gross Total')
    net_pay = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='GBP Order Net Total', default=0.00)
    stripe_fee = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='Stripe Fee', default=0.00)
    platform_fee = models.IntegerField(default=2)
    service_fee = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='Total Service Fee', default=0.00)
    client_email = models.EmailField(max_length=250,blank=True,verbose_name='Client Email')
    trainer_email = models.EmailField(max_length=250,blank=True,verbose_name='Trainer Email')
    created = models.DateTimeField(auto_now_add=True)
    subscription = models.BooleanField(default=False)
    stripe_product_name = models.CharField(max_length=200,default='None')
    stripe_plan_id = models.CharField(max_length=200,default='None')
    #stripe_customer_id = models.CharField(max_length=200,default='None')


    class Meta:
        db_table = 'Order'
        ordering = ['-created'] #to have the most recent order come up first

    def __str__(self):
        return str(self.id)

class OrderItem(models.Model):
    workout = models.CharField(max_length=250)
    sessions = models.IntegerField(default=0)
    trainer_id = models.CharField(max_length=250, default='none')
    client_id = models.CharField(max_length=250, default='none')
    quantity = models.IntegerField()
    price = models.DecimalField(max_digits=10,decimal_places=2,verbose_name='GBP Price')
    order = models.ForeignKey(Order,on_delete=models.CASCADE)
    workout_description = models.TextField(default='There is no description available')

    class Meta:
        db_table = 'OrderItem'
        ordering = ['-id'] #to have the most recent order come up first

    def sub_total(self):
        return self.quantity * self.price

    def __str__(self):
        return self.workout

order/views.py
from django.shortcuts import render,get_object_or_404
from .models import Order, OrderItem
from session.models import Session, AvailableSession
from django.contrib.auth.decorators import login_required

# Create your views here.
@login_required
def thanks(request, order_id):
    if order_id:
        customer_order = get_object_or_404(Order, id=order_id)

    context = {'customer_order': customer_order}
    return render(request, 'order/thanks.html', context)

#client order history
@login_required
def orderHistory(request):
    if request.user.is_authenticated:
        email = str(request.user.email)
        order_details = Order.objects.filter(client_email=email)

    context = {'order_details': order_details}
    return render(request,'order/orders_list.html',context)

@login_required
def viewOrder(request, order_id):
    # user_id = request.user.id

    if request.user.is_authenticated:
        email = str(request.user.email)
        order = Order.objects.get(id=order_id,client_email=email)
        order_items = OrderItem.objects.filter(order=order)

    session = Session.objects.get(order_id=order_id)
    session_id = session.id

    available = AvailableSession.objects.filter(session__id=session_id)

    # total gives hw many sessions they start with
    total = available[0].available_sessions





    context = {'order': order, 'order_items': order_items, 'available': available, 'total': total}
    return render(request, 'order/order_detail.html', context)


#trainer order history
@login_required
def trainerOrderHistory(request):
    if request.user.is_authenticated:
        trainer_id = str(request.user.id)
        trainer_orders = OrderItem.objects.filter(trainer_id=trainer_id)
        print(trainer_orders)

    context = {'trainer_orders':trainer_orders}
    return render(request,'order/trainer_orders_list.html',context)

order/templates/order/order_detail.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
  <h1>Order Details</h1>
  <p>Order Number:{{ order.id }} </p>
  <p>Order Date: {{ order.created|date:"d M Y"}}</p>
  <p>Total Amount:{{ order.total }} </p>
  <br>
  {% for item in order_items%}
  <p>Workout: {{item.workout}}</p>
  <p>Trainer: {{item.order.trainer_name}}</p>
  <p>Quantity: {{item.quantity}}</p>
  <p>Price: {{item.price}}</p>
  <p>Sessions: {{item.sessions}}</p>
  <p>Desctiption: {{item.workout_description}}</p>
  {% endfor %}

  <h3>Session History</h3>
  {% for a in available %}
    {% if a.available_sessions == total %}
      <p>You started with {{ a.available_sessions }} available sessions. created on: {{ a.date }}</p>
    {% else %}
      <p>You have: {{ a.available_sessions }} available sessions. Session last used: {{ a.date }}</p>
    {% endif %}
  {% endfor %}

{% endblock %}

order/templates/order/orders_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

  <h1>Order History </h1>

  {% if order_details %}
    {% for order in order_details %}
    <p>Order Number:{{ order.id }} </p>
    <p>Order Date: {{ order.created|date:"d M Y"}}</p>
    <p>Total Amount:{{ order.total }} </p>
    <!-- <p>Workout: {{ order.orderitem.workout}}</p> -->
    <a href="{% url 'order:order_detail' order.id%}">View Order</a>
    <br>
    <br>
    {% endfor %}
  {% else %}
  <h3>You have not yet placed an order</h3>

  <p> please click <a href="{% url 'gym:trainer_list'%}">Here</a> to find a trainer</p>

  {% endif %}

{% endblock %}

order/templates/order/thanks.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
<h1>Thanks for placing your Order</h1>
<p>Your order number is: <b>{{ customer_order.id }}</b> </p> <br>
<p>We have recieved your order and will begin processing. For your records, an email confirmation has been sent to you.
It contains details of the items you purchased</p>

{% endblock %}

order/templates/order/trainer_orders_list.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}

  <h1>Order History </h1>
  <br>
  <br>

  {% if trainer_orders %}
    {% for order in trainer_orders %}
    <p>Customer Name: {{ order.order.client_name}}</p>
    <p>Order Number:{{ order.id }} </p>
    <p>Order Date: {{ order.order.created|date:"d M Y"}}</p>

    <p>Customer email: {{ order.order.client_email}}</p>
    <p>Number of sessions: {{ order.sessions }}</p>
    <p>Gross Amount:{{ order.order.total }} </p>
    <p>Service Fee: {{ order.order.service_fee }}</p>
    <p>Net Pay:{{ order.order.net_pay }} </p>

    <a href="#">View Order</a>
    <br>
    <br>
    {% endfor %}
  {% else %}
  <h3>You have not yet placed an order</h3>

  <p> please click <a href="{% url 'gym:trainer_list'%}">Here</a> to find a trainer</p>

  {% endif %}

{% endblock %}