cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'
urlpatterns = [
    path('add/<pk>',views.add_cart,name='add_cart'),
    path('',views.cart_detail,name='cart_detail'),
    path('cart/<pk>/remove',views.deleteItem,name='cart_remove'),


]

gym/urls.py
from django.urls import path
from . import views

app_name = 'gym'
urlpatterns = [
    path('',views.TrainerListView.as_view(),name='trainer_list'), #to view list of trainers
    path('client/<pk>/', views.clientProfileView,name='client_profile'), # to view client profile
    path('trainer_profile/', views.trainerProfileView,name='trainer_profile'),
    path('complete/<pk>/', views.complete,name='complete'),
    path('client_pending/', views.clientPendingView,name='client_pending'),
    # path('profile/', views.profileView.statusChange,name='status'),
    path('trainer_register/',views.trainerRegister, name='trainer_signup'),
    path('activate/<uidb64>/<token>/',views.activate, name='activate'),
    # path('stripe_form/',views.stripeForm, name='stripe_form'),
    # path('stripe_register/',views.stripeRegister, name='stripe_register'),
    path('client_register/',views.clientRegister, name='client_signup'),
    path('trainers/<pk>/',views.TrainerDetailView.as_view(),name='trainer_detail'),
    path('client/<pk>/',views.ClientDetailView.as_view(),name='client_detail'), #to update client info
    # path('create/',views.WorkoutCreateView.as_view(),name='workout_create'),
    path('update/<pk>/',views.WorkoutUpdateView.as_view(),name='workout_update'),
    path('trainers/<pk>/workout',views.addWorkout,name='addWorkout'),
    path('workout/<pk>/remove',views.deleteWorkout,name='workout_remove'),
    path('trainer/update/<pk>/',views.TrainerUpdateView.as_view(),name='trainer_update'),
    path('client/update/<pk>/',views.ClientUpdateView.as_view(),name='client_update'),

]

order/urls.py
from django.urls import path
from . import views

app_name = 'order'

urlpatterns = [
    path('thanks/<int:order_id>/',views.thanks,name='thanks'),
    path('history/', views.orderHistory,name='order_history'),
    path('<int:order_id>/', views.viewOrder,name='order_detail'),
    path('history/trainer', views.trainerOrderHistory,name='trainer_order_history'),
]

trainer_project/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('django.contrib.auth.urls')),
    path('',include('gym.urls')),
    path('cart/', include('cart.urls')),
    path('order/', include('order.urls')),
    path('stripe/', include('stripe_details.urls')),
    # path('session/', include('session.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gym/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse



# This helps to seperate trainer accounts from client accounts
class User(AbstractUser):
    is_trainer = models.BooleanField(default=False)
    is_client= models.BooleanField(default=False)


class TrainerProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    name = models.CharField(max_length=100,null=True)
    description = models.TextField()
    age = models.PositiveIntegerField(null=True)
    phone = models.CharField(max_length=30,null=True)
    gender = models.CharField(max_length=30,null=True)
    location = models.CharField(max_length=30,null=True)
    skills = models.CharField(max_length=30,null=True)
    profile_img = models.ImageField(upload_to='profile_image', blank=True)



    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('gym:trainer_detail', kwargs={'pk':self.pk})


class ClientProfile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE,primary_key=True)
    name = models.CharField(max_length=100,null=True)
    goals = models.CharField(max_length=30,null=True)
    age = models.PositiveIntegerField(null=True)
    gender = models.CharField(max_length=30,null=True)
    phone = models.CharField(max_length=30,null=True)
    location = models.CharField(max_length=30,null=True)
    profile_img = models.ImageField(upload_to='profile_image', blank=True)
    stripe_customer_id = models.CharField(max_length=200,default='None')


    def __str__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('gym:client_detail', kwargs={'pk':self.pk})

class Workout(models.Model):
    trainer = models.ForeignKey(TrainerProfile,on_delete=models.CASCADE ,related_name='workouts')
    name = models.CharField(max_length=200,null=True)
    price = models.IntegerField()
    sessions = models.PositiveIntegerField(default=0)
    workout_description = models.TextField(default='There is no description available')
    subscription = models.BooleanField(default=False)


    def get_absolute_url(self):
        return reverse('gym:trainer_detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name

gym/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
from .models import TrainerProfile, User, ClientProfile, Workout


class TrainerSignUpForm(UserCreationForm):

    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_trainer = True
        user.email = self.cleaned_data['email']
        user.save()
        trainer = TrainerProfile.objects.create(user=user)
        return user

class TrainerProfileForm(forms.ModelForm):
    class Meta:
        model = TrainerProfile
        fields = ('name','description','gender','age','phone','location','skills','profile_img')

class ClientSignUpForm(UserCreationForm):
    email = forms.EmailField(required=True)
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_client= True
        user.save()
        trainer = ClientProfile.objects.create(user=user)
        return user

class ClientProfileForm(forms.ModelForm):

    class Meta:
        model = ClientProfile
        fields = ('name','goals','gender','age','phone','location','profile_img')

class WorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = ('name','price','sessions','workout_description','subscription')

gym/views.py
from django.shortcuts import render, redirect, get_object_or_404,HttpResponse
from django.http import Http404
from django.views.generic import (View,TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from .forms import TrainerSignUpForm, TrainerProfileForm,ClientSignUpForm,ClientProfileForm,WorkoutForm
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import User,TrainerProfile, Workout, ClientProfile
from session.models import Session, AvailableSession

from gym.tokens import account_activation_token
from django.template.loader import get_template
from django.core.mail import EmailMessage
from django.contrib.sites.shortcuts import get_current_site

from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode

import requests
from django.conf import settings

import stripe

CLIENT_ID = 'ca_Dht99lrMkYqjCsNZRHznzbcyhCfRzIUm'
STRIPE_TOKEN_URL = 'https://connect.stripe.com/oauth/token'

stripe.api_key = settings.STRIPE_SECRET_KEY
CLIENT_SECRET = settings.STRIPE_SECRET_KEY






@login_required
def clientProfileView(request, pk):


    user_id = request.user.id

##################################### For Clients

    # this filters the most recent order
    session_filter = Session.objects.filter(client_id=user_id).order_by('-id')
    session = session_filter[0]
    session_id = session.id

    # this shows how many availbale session there are
    available = AvailableSession.objects.filter(session__id=session_id)

    total = available[0].available_sessions


    # i might be able to delete this
    latest_available = available.latest('id')


    # change status to pending or complete
    def statusChange():
        session.status = 'pending'
        session.save()


    if (request.GET.get('use_session')):
        statusChange()
        # createAvailabeSession()
        return redirect('gym:client_profile',pk=user_id) #move to pending page
    else: # probably change status to complete
        print('nothing to see here')
        pass

    context = {'session': session, 'available': available, 'total': total}
    return render(request, 'gym/clientprofile_detail.html', context)


# currently not being used
@login_required
def clientPendingView(request):

    return render(request, 'gym/client_pending.html')



@login_required
def complete(request, pk):
    user_id = request.user.id

    session= Session.objects.get(pk=pk)
    session_id=session.id

    # this shows how many availbale session there are
    available = AvailableSession.objects.filter(session__id=session_id)
    for a in available:
        print(a.date)

    def createAvailabeSession():
        available_session = a.available_sessions


        if session.status == 'pending' and available_session == 1:
            available_session -= 1
            new_session = available_session


            if session.status == 'pending':
                a_s = AvailableSession.objects.create(
                        session = session,
                        available_sessions = new_session
                        )
                a_s.save()
                print(available_session)
                session.status = 'complete'
                session.save()

        elif session.status == 'pending' and available_session > 1:
            available_session -= 1
            new_session = available_session


            if session.status == 'pending':
                a_s = AvailableSession.objects.create(
                        session = session,
                        available_sessions = new_session
                        )
                a_s.save()
                print(available_session)
                session.status = 'available'
                session.save()

        else:
            print('you have no more workouts')


    createAvailabeSession()
    return redirect('gym:trainer_profile')


@login_required
def trainerProfileView(request):

    user_id = request.user.id




    # when the 'confirm_session' button is pressed
    if (request.GET.get('confirm_session')):
        # statusChange()
        # createAvailabeSession()
        return redirect('gym:client_profile',pk=user_id) #move to pending page
    else: # probably change status to complete
        print('nothing to see here')
        pass

    # this filters all sessions linked to the trainer
    session_filter = Session.objects.filter(trainer_id=user_id).order_by('-id')

    # print all status
    # for session in session_filter:
    #     print(session.status)

    session_id = []
    for session in session_filter:
            session_id.append(session.id)

    print(session_id)



    available_info = []
    # for each session in the session id
    for session in session_id:
        available = AvailableSession.objects.filter(session__id=session)
        # add the number of available sessions?
        for a in available:
            # print(a.available_sessions)
            available_info.append(a)

    # # get stripe id public and secret key
    # if (request.GET.get('stripe_register')):
    #     def createStripeAcct():
    #         acct = stripe.Account.create(
    #             country="GB",
    #             type="custom"
    #             )
    #         acct_id = acct.id
    #         acct_keys = acct.items
    #         for x, y in acct_keys():
    #             if x == 'keys':
    #                 pub = y['publishable']
    #                 sec = y['secret']
    #         return acct_id, pub, sec
    #
    #
    #     stripe_deets = createStripeAcct()
    #     print(stripe_deets)
    #
    #     trainerprofile = TrainerProfile.objects.get(pk=user_id)
    #     trainerprofile.stripe_id = stripe_deets[0]
    #     trainerprofile.stripe_pub_key = stripe_deets[1]
    #     trainerprofile.stripe_secret_key = stripe_deets[2]
    #     trainerprofile.save()
    #
    #
    #
    #     # statusChange()
    #     # # createAvailabeSession()
    #     # return redirect('gym:client_profile',pk=user_id) #move to pending page
    # else: # probably change status to complete
    #     print('nothing to see here')
    #     pass

    context = {'session_filter': session_filter, 'available_info': available_info}
    return render(request,'gym/trainer_profile.html', context)



class TrainerListView(ListView):
    context_object_name = 'trainers'
    model = TrainerProfile

class TrainerDetailView(DetailView):
    context_object_name = 'trainer_detail'

    model = TrainerProfile
    template_name = 'gym/trainer_detail.html'

class ClientDetailView(DetailView):
    context_object_name = 'client_detail'

    model = ClientProfile
    # template_name = 'gym/client_profile.html'



class TrainerUpdateView(LoginRequiredMixin,UpdateView):
    model = TrainerProfile
    fields = ('profile_img','skills','location','phone')

class WorkoutCreateView(LoginRequiredMixin,CreateView):

    model = Workout
    fields = ('trainer','name','price','sessions','subscription')

class WorkoutUpdateView(LoginRequiredMixin,UpdateView):
    model = Workout
    fields = ('name','price','sessions','workout_description','subscription')

    # def product_id():
    #     product = stripe.Product.create(
    #     name='My SaaS Platform',
    #     type='service',
    #     )
    #
    #     return product.id
    #
    # if model.subscription == 1:
    #     product_id = product_id()
    #     print(product_id)

class ClientUpdateView(LoginRequiredMixin,UpdateView):
    model = ClientProfile
    fields = ('profile_img','name','location','phone')



# if subscription == 1:
#     product = stripe.Product.create(
#     name='My SaaS Platform',
#     type='service',
#     )
#     print(product.id)
# else:
#     pass


@login_required
def addWorkout(request,pk):
    trainerProfile = get_object_or_404(TrainerProfile,pk=pk)
    trainer_pk = trainerProfile.pk
    if request.method == 'POST':
        form = WorkoutForm(request.POST)
        if form.is_valid():
            workout = form.save(commit=False)
            workout.trainer = trainerProfile
            workout.save()
            return redirect('gym:trainer_detail',pk=trainer_pk)
    else:
        form = WorkoutForm()

    context = {'form':form}

    return render(request,'gym/workout_form.html',context)

@login_required
def deleteWorkout(request,pk):
    workout = get_object_or_404(Workout,pk=pk)
    trainer_pk = workout.trainer.pk
    workout.delete()
    return redirect('gym:trainer_detail',pk=trainer_pk)





def trainerRegister(request):
    if request.method == 'POST':
        form = TrainerSignUpForm(request.POST)
        profile_form = TrainerProfileForm(request.POST, request.FILES)

        if form.is_valid() and profile_form.is_valid():
            user = form.save()
            user.is_active = False
            user.save()
            profile = profile_form.save(commit=False)
            profile.user = user
            profile.save()

            email = form.cleaned_data['email']
            current_site = get_current_site(request)
            sendActivationEmail(email, user, current_site)
            return HttpResponse('Please confirm your email address to complete the registration. Check your junk mail if email not in inbox')
    else:
        form = TrainerSignUpForm()
        profile_form = TrainerProfileForm()

    context = {'form': form, 'profile_form': profile_form}
    return render(request,'registration/trainer_signup_form.html', context)




# def stripeForm(request):
#
#     url = 'https://connect.stripe.com/oauth/authorize?response_type=code&client_id={}&scope=read_write'.format(CLIENT_ID)
#
#     user = request.user
#
#     code = request.GET.get('code')
#     # print('new',code)
#     data = {'client_secret': CLIENT_SECRET,'code': code,'grant_type':'authorization_code'}
#     r = requests.post(STRIPE_TOKEN_URL, data=data)

gym/templates/gym/client_pending.html
{% extends 'base.html' %}

{% block content %}
<p>Waiting for trainer to approve</p>]

{% endblock %}

gym/templates/gym/client_profile.html
{% extends 'base.html' %}

{% block content %}

  {% if user.is_client == True %}


    <h1>Welcome Client: {{ user.username }}</h1>
    {% if user.clientprofile.profile_img %}
      <img src="{{user.clientprofile.profile_img.url}}" width="240" alt="No Image">
    {% endif %}
    <h2>Sessions</h2>
    <p>get the most recent order id</p>
    <p>model to have available sessions, normal sessions, date, status</p>
    <p>if button is pushed, status is changed from unused to pending, second button appears in trainer</p>
    <p>if button is accepted, status is changed to completed</p>
    <p>when status is changed to completed new object of AvailableSession is created, status changed back to available</p>
    <p>when availble sessions reaches zero sessions is filed away</p>
    <br>
    <br>
    <br>
    <p>Your newest order is: {{ session.order_id }} from {{ session.order.trainer_name}}</p>
    {% for a in available %}
    <p>You have: {{ a.available_sessions }} available sessions. last used: {{ a.date }}</p>
    {% endfor %}
    <form method="get">
    <input type="submit" class="btn btn-primary" value="Use Session" name="use_session">
    </form>

  {% else %}
  <p>You are not a client</p>

  {% endif %}


{% endblock %}

gym/templates/gym/clientprofile_detail.html
{% extends 'base.html' %}

{% block content %}

  {% if user.is_client == True %}


    <h1>Welcome Client: {{ user.username }}</h1>
    {% if user.clientprofile.profile_img %}
      <img src="{{user.clientprofile.profile_img.url}}" width="240" alt="No Image">
    {% endif %}
    <h2>Sessions</h2>
    <p>get the most recent order id</p>
    <p>model to have available sessions, normal sessions, date, status</p>
    <p>if button is pushed, status is changed from unused to pending, second button appears in trainer</p>
    <p>if button is accepted, status is changed to completed</p>
    <p>when status is changed to completed new object of AvailableSession is created, status changed back to available</p>
    <p>when availble sessions reaches zero sessions is filed away</p>
    <br>
    <br>
    <br>
    {% if session.status == 'complete'%}
      <p>Congratulations you've completed your workout</p>
      <p>Book another: <a href="{% url 'gym:trainer_detail' pk=session.trainer_id%}">Here</a> </p>
      <p>Checkout your workout history <a href="{% url 'order:order_history'%}">Here</a> </p>
    {% else %}
      <p>Your newest order is: {{ session.order_id }} from {{ session.order.trainer_name}}</p>
      {% for a in available %}
        {% if a.available_sessions == total %}
          <p>You started with {{ a.available_sessions }} available sessions. created on: {{ a.date }}</p>
        {% else %}
          <p>You have: {{ a.available_sessions }} available sessions. Session last used on: {{ a.date }}</p>
        {% endif %}
      {% endfor %}
      <a class="btn btn-primary" href="mailto:{{ session.order.trainer_email}}">Request Session</a>
      <p>Email: {{ session.order.trainer_email}}</p>
        <form method="get">
          <input type="submit" class="btn btn-primary" value="Attend Session" name="use_session">
        </form>

    <br>
    <br>

    {% endif %}
  <p> <a class="btn btn-success" href="{% url 'gym:client_update' pk=user.pk %}">Update Profile</a> </p>
  {% else %}
  <p>You are not a client</p>

  {% endif %}


{% endblock %}

gym/templates/gym/clientprofile_form.html
{% extends 'base.html'%}

{% block content %}



<h1>Update Profile</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" name="" value="Update">

</form>



{% endblock %}

gym/templates/gym/profile.html
{% extends 'base.html' %}

{% block content %}
  {% if user.is_trainer == True %}
    <h1>Welcome Trainer: {{ user.username }}</h1>
  {% else %}
    <h1>Welcome Client: {{ user.username }}</h1>
    {% if user.clientprofile.profile_img %}
      <img src="{{user.clientprofile.profile_img.url}}" width="240" alt="No Image">
    {% endif %}
    <h2>Sessions</h2>
    <p>get the most recent order id</p>
    <p>model to have available sessions, normal sessions, date, status</p>
    <p>if button is pushed, status is changed from unused to pending, second button appears in trainer</p>
    <p>if button is accepted, status is changed to completed</p>
    <p>when status is changed to completed new object of AvailableSession is created, status changed back to available</p>
    <p>when availble sessions reaches zero sessions is filed away</p>
    <br>
    <br>
    <br>
    <p>Your newest order is: {{ session.order_id }}</p>
    {% for a in available %}
    <p>You have: {{ a.available_sessions }} available sessions</p>
    <!-- <p> Used on {{ a.date }} </p> -->

    {% endfor %}
    <form method="get">
    <input type="submit" class="btn btn-primary" value="Use Session" name="use_session">
    </form>


  {% endif %}
{% endblock %}

gym/templates/gym/trainer_detail.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content%}
<div class="jumbotron">
  <h2>Trainer Details: </h2>
  {% if trainer_detail.profile_img %}
    <img src="{{trainer_detail.profile_img.url}}" width="240" alt="No Image">

  {% endif %}

  <p>Name: {{trainer_detail.user.username }}</p>
  <p>Description: {{trainer_detail.description}}</p>
  <p>Age: {{ trainer_detail.age }}</p>
  <p>Skills: {{ trainer_detail.skills }}</p>
  <p>Location: {{ trainer_detail.location}}</p>
  <p>Email: {{ trainer_detail.user.email }}</p>

  <h2>Workouts</h2>

<!-- this is the view if the user is a trainer viewing their own detail page-->
  {% if user.trainerprofile.pk == trainer_detail.pk %}
  <form action="{% url 'gym:trainer_detail' pk=trainer_detail.pk %}" method="POST">
    {% csrf_token %}
    {% for workout in trainer_detail.workouts.all %}
    {{ workout.name }}: £{{ workout.price }}
    <br>
    Number of Sessions per month: {{workout.sessions }}
    <br>
    Description: {{ workout.workout_description}}
    <input type="radio" name="workout" value="{{ workout.price }}">
    <p> <a class="btn btn-warning" href="{% url 'gym:workout_update' pk=workout.pk %}">Update</a>  <a class="btn btn-warning" href="{% url 'gym:workout_remove' pk=workout.pk %}">Delete</a> </p>

    <br>

    {% endfor%}
</form>

</div>

<div class="container">
  <p> <a class="btn btn-success" href="{% url 'gym:addWorkout' pk=trainer_detail.pk %}">Add New Workout</a> </p>
  <p> <a class="btn btn-success" href="{% url 'gym:trainer_update' pk=trainer_detail.pk %}">Update Profile</a> </p>
</div>
<!-- this is the view if the user is a client -->
  {% else %}
  <form action="{% url 'gym:trainer_detail' pk=trainer_detail.pk %}" method="GET">
    {% csrf_token %}

    {% for workout in trainer_detail.workouts.all %}
    {{ workout.name }}: £{{ workout.price }}
    <br>
    Number of Sessions per month: {{workout.sessions }}
    <br>
    Description: {{ workout.workout_description}}
    <a class="btn btn-primary" href="{% url 'cart:add_cart' pk=workout.pk %}">Add To Cart</a>
    <br>

    {% endfor%}
</form>
{% endif %}






{% endblock %}

gym/templates/gym/trainer_profile.html
{% extends 'base.html' %}

{% block content %}
  {% if user.is_trainer == True %}
    <h1>Welcome Trainer: {{ user.username }}</h1>

    {% if user.trainerprofile.profile_img %}
      <img src="{{user.trainerprofile.profile_img.url}}" width="240" alt="No Image">
    {% endif %}

    <br>
    <br>
    <h2>Sessions</h2>
    <p>get all available or pending sessions</p>
    <p>model to have available sessions, normal sessions, date, status</p>
    <p>If offer is pending then button to complete or cancel</p>
    <p>when status is changed to completed</p>
    <p>when availble sessions reaches zero sessions is filed away</p>
    <br>
    <br>
    <br>
    <p>PENDING QUEUE</p>
    <br>
    {% for session in session_filter %}
      {% if session.status == 'pending' %}
      <form method="GET">
        {% csrf_token %}
        Status: {{ session.status}} <br>
        {{ session.order.client_name}} has requested to use a {{ session.workout_name }} session

        <a class="btn btn-primary" href="{% url 'gym:complete' pk=session.pk %}">Confirm Session</a>
        </form>
        <br>
        <br>
      {% endif %}

    {% endfor %}
    <br>
    <br>
    <h3>All Clients Which Are Available</h3>
    {% for session in session_filter %}
      {% if session.status == 'available' %}
        <h4>{{ session.order.client_name}} booked {{ session.total_sessions}} workouts of {{session.workout_name}} on {{session.date}}<br></h4>
        {% for a in available_info %}
          {% if a.session_id == session.id %}
          There are {{a.available_sessions}}workouts left. Last workout took place on {{ a.date}}<br>
          {% endif %}

        {% endfor %}



      {% endif %}

    {% endfor%}
    <br>
    <br>
    <br>



  {% else %}
  <p>You are not a trainer</p>

  {% endif %}
{% endblock %}

gym/templates/gym/trainerprofile_form.html
{% extends 'base.html'%}

{% block content %}



<h1>Update Profile</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" name="" value="Update">

</form>



{% endblock %}

gym/templates/gym/trainerprofile_list.html
{% extends 'base.html' %}

{% block content %}
<h1>List Of Trainers</h1>

  {% if not trainers %}
  <p>There are no trainers</p>
  {% else %}
  <ol>
    {% for trainer in trainers %}
    <h2> <li><a href="{% url 'gym:trainer_detail' pk=trainer.pk %}">{{ trainer.user.username }}</a> </li> </h2>
    {% endfor%}
  </ol>

  {% endif %}

{% endblock %}

gym/templates/gym/workout_form.html
{% extends 'base.html'%}

{% block content %}


{% if not form.instance.pk %}
<h1>Add A Workout</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}


  <input type="submit" class="btn btn-primary" name="" value="Add">

</form>

{% else %}
<h1>Update Workout</h1>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" class="btn btn-primary" name="" value="Update">

</form>
{% endif %}


{% endblock %}